### ISSUE TITLE
Need a workaround for enabling the commented step in the CTS Search Result Page Test feature file

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#137]
### Issue description

We need a workaround for enabling the commented step in the Search Result Page Test feature file. The step that is commented on SearchResultsPageTests.feature is:

 "And there are 2 delighters present"

We are currently getting the following error for it:
![image](https://user-images.githubusercontent.com/28455973/149394215-ec4152c0-700e-4ef3-bd22-06b66432cbc3.png)

Also commented out Print scenario - this is a manual step for now

 

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
- Currently, we have commented the step in the SearchResultsPageTests.feature  file.

The code for that step which can be found in the index,js is:
![image](https://user-images.githubusercontent.com/28455973/149394636-16261cf9-3f38-4557-8386-d5eeafa30bab.png)

### What's the updated acceptance criteria
We need a workaround code so that the step that has been commented executes without error.

```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by KateMashkinaNIH** [comment]
delighters are killed with redesign MVP1
