### ISSUE TITLE
Story: Infographics tests

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform-acceptance-tests#146]
## As a user, I want to be able to view and interact with infographic media

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario Outline: Infographics general visible components
  Given user is navigating to "<url>"
    Then infographic's picture element is displayed
  And infographic has a caption "<caption>"
  And the "View and Print Infographic" button is displayed

Examples:
|url| caption|
||
```

```gherkin
Scenario Outline: Infographics attributes
 Given user is navigating to "<url>"
 Then infographic's picture element is displayed
 And infographic has an alt text "<altText>"
And infographic has a long description attribute "<longdesc>"
And infographic has a data title attribute "<title>"
Examples:
|url| altText| longdesc | title|


```

```gherkin
Scenario Outline: Infographics can be open in a view and print preview window
 Given user is navigating to "<url>"
 Then infographic's picture element is displayed
 And infographic "View and Print Infographic" button's link has an href "<href>"
And infographic "View and Print Infographic" button has a blank target attribute

Examples:
|url| altText| longdesc |


```

```gherkin
Scenario Outline: Infographics has mobile and desktop versions where enabled
 Given user is navigating to "<url>"
 Then infographic's picture element is displayed
 And infographic's picture source has srcset attribute with value "<desktopSrcSet>" and media attribute "(min-width: 769px)"
And infographic's picture source has srcset attribute with value "<mobileSrcSet>" and media attribute "(max-width: 768px)"

Examples:
|url| desktopSrcSet| mobileSrcSet |


```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* none of the attr's value should include `?itok=` part ( so you can do a string equality safely) 
* add examples

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by kate-mashkina** [comment]
Closing this as the tests already exist https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/blob/master/cypress/integration/FullInfographicPage.feature
