### ISSUE TITLE
Testing Updates for Mobile and Section Nav API

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform-acceptance-tests#250]
This is to support https://github.com/NCIOCPL/cgov-digital-platform/issues/3604

- [ ] There is a task to update tests to support the new data elements
- [ ] It also looks like we have some gaps:
   - [x] Test Spanish content
   - [x] Fix the term id of A.4
   - [x] Missing 400 tests:
      - [x] Ask for a section nav that is not is_section_nav_root
      - [x] Ask for a mobile nav that is not is_mobile_nav_root
      - [x] Ask for a section nav that is missing a landing page, has an unpublished landing page, 
      - [x] Ask for a mobile nav that is missing a landing page, has an unpublished landing page,

**Comment by KateMashkinaNIH** [comment]
this is done
