### ISSUE TITLE
CMS: Mini Landing Page Verifications (used in Home & Landing Page)

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#256]
##As a CMS user, I want to verify that Mini Landing page used in different content types (e.g. Home & Landing page) appear correctly on Feature cards in other content type (e.g. e.g Home & Landing page).

In order to verify Mini Landing Page functionality when it is used in other content type, the newly created  Mini Landing Page should be added to the Home Landing page using Add Primary Feature Card Row -> Internal feature Card.
There should be a feature that will include a scenario to create a Home & Landing page, add a test url of the newly created  Mini Landing Page into Internal Feature Card, publish and verify that the Promo image and the Feature Card Description that is used in  Mini Landing Page appears correctly on the Primary Feature Card in the newly created the home & landing page.

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by KateMashkinaNIH** [comment]
I am adding this as part of home and landing feature

**Comment by santwuma** [comment]
Duplicate ticket
