### ISSUE TITLE
CMS: Article Verifications (used in Home & Landing Page, Mini landing Page)

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#257]
## As a CMS user, I want to verify that Article used in different content types (e.g. Home & Landing page and Mini Landing page) appear correctly on Feature cards in other content type (e.g. Home & Landing page and Mini Landing page).

In order to verify promotional images, card etc. used in Article and to verify the functionality of an article, the newly created article should be added to the
a) Mini Landing page using Add Content Block -> Add Two Item Feature Card Row-> Internal feature Card.
b) Home Landing page using Add Primary Feature Card Row -> Internal feature Card.

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by KateMashkinaNIH** [comment]
This is already a part of feature files in Mini Landing and Home & Landing

**Comment by santwuma** [comment]
Duplicate ticket
