### ISSUE TITLE
Update to Production Smoke Tests

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform-acceptance-tests#318]
### Issue description
*Description of the issue.*
1. SBIR.feature: Update Mega menu title "Commercialize Your Technology" to "Commercialization"
2. GeneralTests.feature: Update NCIConnect mega menu title "NCI-CONNECTions" to "NCI-CONNECTions Blog"
3. Fix the R4R api version. Getting this error: 

https://webapis.cancer.gov/r4r/v1//resources?from=0&toolTypes=analysis_tools
The response we received from your web server was:
  > 404: Not Found
This was considered a failure because the status code was not `2xx` or `3xx`.
If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

### Additional details / screenshot
- ![Screenshot]()
- 
![image](https://user-images.githubusercontent.com/31008800/208950949-9da7b839-1d14-4634-9c85-9d81c0b503c4.png)

![image](https://user-images.githubusercontent.com/31008800/208951006-81d4f7df-03d7-477a-8cfb-eef56e1608a6.png)

![image](https://user-images.githubusercontent.com/31008800/208951053-96e02443-d146-4e42-b135-23509f629bbe.png)

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by santwuma** [comment]
Duplicate ticket #319 - closing
