### ISSUE TITLE
Story: Story: Borderless Full-Width Card test

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/cgov-digital-platform-acceptance-tests#33]
## As a content editor, I would like to be able to embed a borderless full-width card, so that we can promote the most important information effectively.

> **ESTIMATE** 20

### Acceptance Criteria

```gherkin
Scenario Outline: User views a page with a borderless full-width card on desktop or tablet 
  Given user is navigating to "/borderlessCardURL" 
 And screen breakpoint is set to "desktop"
    And the page title of the feature card <"cardNumber"> is <"cardTitle">
    And the feature card <"cardNumber"> title will have the href "<titleHref">
    And the feature card <"cardNumber"> description is <"cardDescription">
    And the feature card <"cardNumber"> will have a button displayed under the card description with the text <"buttonText"> and href <"titleHref">
    And 610 by 610 sized promo image of the feature card <"cardNumber"> is displayed with the source <"promoImageSource"> and alt text <"promoImageAlt">
    And the feature card <"cardNumber"> promo image will link to the <"titleHref">

Examples:
|cardNumber|titleHref|cardDescription|buttonText|promoImageSource|promoImageAlt|
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by KateMashkinaNIH** [comment]
merged
