### ISSUE TITLE
CMS: Translation of Blog post

### ISSUE THREAD

**Issue by KateMashkinaNIH** [NCIOCPL/cgov-digital-platform-acceptance-tests#381]
## As a [role], I want [feature], so that [benefit]

> **ESTIMATE** TBD

### Acceptance Criteria
Instruction:
1. Add the following scenarios in $BlogPosts.feature just after the
Scenario: Remove featured item
2. The"Scenario: Clean up" in the existing $BlogPosts.feature will replace the "Scenario: Clean up" in this ticket.
```gherkin

Scenario: Add a translation
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        Then user selects "Translate" option from Operations dropdown for content with title "Automated Test Blog Post Edited"
        Then the page title is "Translations of Automated Test Article Edited"
        When user clicks on "Add" button to add translation
        Then page title is "Crear traducción Español de Automated Test Blog Post Edited"
        And "Blog Series" dropdown displays "Temas y relatos blog"
        And the following fields are displayed
            | fieldLabel               | field_name                     |
            | Pretty URL               | field_pretty_url               |
            | Título de página         | title                          |
            | Browser Title            | field_browser_title            |
            | Card Title               | field_card_title               |
            | Meta Description         | field_page_description         |
            | Feature Card Description | field_feature_card_description |
        And "List Description" label is displayed
        And Author was translated as "Autor"
        And "Intro Text" label is displayed
        And body was translated as "Cuerpo"
        And "Lead Image" button is displayed
        And Remove button for image was translated as "Eliminar"
        And "Promotional Image" button is displayed
        And the following fields are displayed under "Blog Topic" label
            | blogTopic                                  |
            | Biología                                   |
            | Riesgo de cáncer                           |
            | Cáncer infantil                            |
            | Resultados de estudios clínicos            |
            | Desigualdades                              |
            | Aprobaciones de la FDA                     |
            | Salud mundial                              |
            | Dirección y opiniones de expertos          |
            | Prevención                                 |
            | Pronóstico                                 |
            | Exámenes de detección y detección temprana |
            | Supervivencia y cuidados de apoyo          |
            | Tecnología                                 |
            | Tratamiento                                |
        And Related Resources section was translated as "Recursos relacionados"
        And Link section under related resources was translated as "Enlace"
        And dropdown to add link under related resources was translated to start with "Añadir"
        And "Recommended Content" label is displayed
        And Link section under recommended content is displayed as "Featured Item"
        And dropdown to add link under recommended content was translated to start with "Añadir"
        And button to add citation was translated as "Añadir Citation"
        And "Public Use Text" dropdown has the following options
            | options        |
            | - Ninguno -    |
            | Presentación   |
            | Do Not Display |
        And "Public Use Text" dropdown displays "Do Not Display"
        And "Search Engine Restrictions" dropdown displays "Include in search"
        And "Posted Date" label is displayed
        And current state was translated as "Estado actual" "Borrador"
        And Change to dropdown has the following options
            | option    |
            | Borrador  |
            | Review    |
            | Publicado |
        And Save button was translated as "Guardar (esta traducción)"
        And preview button was translated as "Vista previa"
        Then user saves the content page
        And user clicks on the tool bar status green button "Borrador"
        And user selects "Quick Publish" from workflow actions

    Scenario: Verify translated content
        Given user is navigating to the front end site with spanish path "/espanol" site section plus "/noticias/temas-y-relatos-blog/{YEAR}/blog-post-edited"
        Then page title is "Automated Test Blog Post Edited"
        And blog's posted date is today's date
        And the "Suscríbase" button appears
        And the "Archivo" accordion is displayed
        And the lead image is matching the earlier selected image
        And blog posts list doesnot appear in the archive
        And "< Artículo anterior" link appears
        When user clicks on "< Artículo anterior" link
        And "Artículo siguiente >" link appears
        When user clicks on "Artículo siguiente >" link
        Then the author name "Automated Test Blog Post Author" is displayed
        And intro text reads "Blog Post Intro Text"
        And description reads "This is a description of Blog Post content type."
        And the lead image is matching the earlier selected image
        Then Recursos relacionados section contains the following links
            | title                             | link                          |
            | Article to test Related Resources | {TEST_SITE_SECTION}/article   |
            | Google Link                       | https://www.google.com/       |
            | Media Link Override Title         | {TEST_SITE_SECTION}/test-file |
        Then Recommended Content section contains the following links
            | title                             | link                        |
            | Article to test Related Resources | {TEST_SITE_SECTION}/article |
            | Google Link                       | https://www.google.com/     |
  
  Scenario: Edit and republish Spanish blog post content type
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        And user clicks on title with url spanish path "/espanol" site section plus "noticias/temas-y-relatos-blog/{YEAR}/blog-post-edited"
        And user clicks on the tool bar status green button "Publicado"
        And user clicks "View in edit form" button from other actions
        And user clears out "Título de página" field
        And user clears out "Meta Description" field
        And user fills out the following fields
            | fieldLabel       | value                                                  | field_name             |
            | Título de página | Automated Test Article Edited Spanish                  | title                  |
            | Meta Description | Automated Test Article Meta Description Edited Spanish | field_page_description |
        When user saves the content page
        And user clicks on the tool bar status green button "Editing"
        And user selects "Quick Publish" from workflow actions
   
 Scenario: Verify Spanish edited content
        Given user is navigating to the front end site with spanish path "/espanol" site section plus "test-article-edited"
        And browser waits
        Then page title is "Automated Test Article Edited Spanish"
        And the page contains meta tags with the following names
            | name        | content                                                |
            | description | Automated Test Article Meta Description Edited Spanish |
    
Scenario: Clean up
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        And user selects a checkbox next to title with url "blog-post-edited" under "/news-events/cancer-currents-blog" from the list of content
        And user clicks on "Apply to selected items" content action button
        Then page title is "Are you sure you want to delete this content item?"
        When user clicks on "Delete" button
        Then the confirmation text "Deleted 2 content item." appears on a screen
        And the content item with url "blog-post-edited" does not exist in the list of content
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by alinai** [comment]
@ahmadakbaryNIH , I have deleted the duplicated step and replaced "Article" with "Blog Post" wherever it is needed: 
    Scenario: Add a translation
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        Then user selects "Translate" option from Operations dropdown for content with title "Automated Test Blog Post Edited"
        Then the page title is "Translations of Automated Test Blog Post Edited"
        When user clicks on "Add" button to add translation
        Then page title is "Crear traducción Español de Automated Test Blog Post Edited"
        And "Blog Series" dropdown displays "Temas y relatos blog"
        And the following fields are displayed
            | fieldLabel               | field_name                     |
            | Pretty URL               | field_pretty_url               |
            | Título de página         | title                          |
            | Browser Title            | field_browser_title            |
            | Card Title               | field_card_title               |
            | Meta Description         | field_page_description         |
            | Feature Card Description | field_feature_card_description |
        And "List Description" label is displayed
        And Author was translated as "Autor"
        And "Intro Text" label is displayed
        And body was translated as "Cuerpo"
        And "Lead Image" button is displayed
        And Remove button for image was translated as "Eliminar"
        And "Promotional Image" button is displayed
        And the following fields are displayed under "Blog Topic" label
            | blogTopic                                  |
            | Biología                                   |
            | Riesgo de cáncer                           |
            | Cáncer infantil                            |
            | Resultados de estudios clínicos            |
            | Desigualdades                              |
            | Aprobaciones de la FDA                     |
            | Salud mundial                              |
            | Dirección y opiniones de expertos          |
            | Prevención                                 |
            | Pronóstico                                 |
            | Exámenes de detección y detección temprana |
            | Supervivencia y cuidados de apoyo          |
            | Tecnología                                 |
            | Tratamiento                                |
        And Related Resources section was translated as "Recursos relacionados"
        And Link section under related resources was translated as "Enlace"
        And dropdown to add link under related resources was translated to start with "Añadir"
        And "Recommended Content" label is displayed
        And Link section under recommended content is displayed as "Featured Item"
        And dropdown to add link under recommended content was translated to start with "Añadir"
        And button to add citation was translated as "Añadir Citation"
        And "Public Use Text" dropdown has the following options
            | options        |
            | - Ninguno -    |
            | Presentación   |
            | Do Not Display |
        And "Public Use Text" dropdown displays "Do Not Display"
        And "Search Engine Restrictions" dropdown displays "Include in search"
        And "Posted Date" label is displayed
        And current state was translated as "Estado actual" "Borrador"
        And Change to dropdown has the following options
            | option    |
            | Borrador  |
            | Review    |
            | Publicado |
        And Save button was translated as "Guardar (esta traducción)"
        And preview button was translated as "Vista previa"
        Then user saves the content page
        And user clicks on the tool bar status green button "Borrador"
        And user selects "Quick Publish" from workflow actions

    Scenario: Verify translated content
        Given user is navigating to the front end site with spanish path "/espanol" site section plus "/noticias/temas-y-relatos-blog/{YEAR}/blog-post-edited"
        Then page title is "Automated Test Blog Post Edited"
        And blog's posted date is today's date
        And the "Suscríbase" button appears
        And the "Archivo" accordion is displayed
        And the lead image is matching the earlier selected image
        And blog posts list doesnot appear in the archive
        And "< Artículo anterior" link appears
        When user clicks on "< Artículo anterior" link
        And "Artículo siguiente >" link appears
        When user clicks on "Artículo siguiente >" link
        Then the author name "Automated Test Blog Post Author" is displayed
        And intro text reads "Blog Post Intro Text"
        And description reads "This is a description of Blog Post content type."
        Then Recursos relacionados section contains the following links
            | title                             | link                          |
            | Article to test Related Resources | {TEST_SITE_SECTION}/article   |
            | Google Link                       | https://www.google.com/       |
            | Media Link Override Title         | {TEST_SITE_SECTION}/test-file |
        Then Recommended Content section contains the following links
            | title                             | link                        |
            | Article to test Related Resources | {TEST_SITE_SECTION}/article |
            | Google Link                       | https://www.google.com/     |

    Scenario: Edit and republish Spanish blog post content type
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        And user clicks on title with url spanish path "/espanol" site section plus "noticias/temas-y-relatos-blog/{YEAR}/blog-post-edited"
        And user clicks on the tool bar status green button "Publicado"
        And user clicks "View in edit form" button from other actions
        And user clears out "Título de página" field
        And user clears out "Meta Description" field
        And user fills out the following fields
            | fieldLabel       | value                                                    | field_name             |
            | Título de página | Automated Test Blog Post Edited Spanish                  | title                  |
            | Meta Description | Automated Test Blog Post Meta Description Edited Spanish | field_page_description |
        When user saves the content page
        And user clicks on the tool bar status green button "Editing"
        And user selects "Quick Publish" from workflow actions

    Scenario: Verify Spanish edited content
        Given user is navigating to the front end site with spanish path "/espanol" site section plus "test-article-edited"
        And browser waits
        Then page title is "Automated Test Blog Post Edited Spanish"
        And the page contains meta tags with the following names
            | name        | content                                                  |
            | description | Automated Test Blog Post Meta Description Edited Spanish |

    Scenario: Clean up
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Content" tab
        And user selects a checkbox next to title with url "blog-post-edited" under "/news-events/cancer-currents-blog" from the list of content
        And user clicks on "Apply to selected items" content action button
        Then page title is "Are you sure you want to delete this content item?"
        When user clicks on "Delete" button
        Then the confirmation text "Deleted 2 content item." appears on a screen
        And the content item with url "blog-post-edited" does not exist in the list of content
