### ISSUE TITLE
Update reference images due to NCIDS Feature Card Multimedia changes

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#524]
### Issue description
Description of what is to be accomplished.
Need to regenerate backstop images - here is a run https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/5556515301

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by KateMashkinaNIH** [comment]
this is part of 525
