### ISSUE TITLE
Update texts in Internal and External Link Buttons 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#531]
### Issue description
 The (Override) Link Button Title field on Internal and External Link Buttons has been changed so that the (Override) Link Button Title field allows 100 characters. So the button text has been changed in yaml. We need to update our tests to accommodate it.

> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

**Comment by KateMashkinaNIH** [comment]
this change was addressed in #528
