### ISSUE TITLE
Story: CIS and DIS glossary pop-ups

### ISSUE THREAD

**Issue by kate-mashkina** [NCIOCPL/cgov-digital-platform-acceptance-tests#66]
## As a user I want to view definition pop-ups when available while visiting cancer info summary and drug info summary pages

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario Outline: PDQ Information summary glossary links
        Given user is navigating to "<url>"
        When user is clicking on definition for "<termName>"
        Then pop-up definition box is displayed for "<termName>"
        And definition box displays all "<features>" provided by glossary

        Examples:
            | url                                        | termName | features                                |
            | /types/breast/patient/breast-treatment-pdq | breast   | definition,pronunciation,audio,img[2] |
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

**Comment by alinai** [comment]
@kate-mashkina , here are some more urls for adding to the Examples table in the AC:
Examples
| url                                        | termName | features                                |
 |/types/breast/patient/breast-treatment-pdq | breast   | definition,pronunciation,audio,img[2] |
|/espanol/tipos/seno/paciente/tratamiento-seno-pdq|mama| definition,audio,img[2]|
|/types/breast/hp/breast-ovarian-genetics-pdq|chromosome|definition,pronunciation,audio,img[1]|
|/types/breast/patient/breast-screening-pdq| genetic testing|definition,pronunciation,audio|
|/espanol/tipos/seno/paciente/deteccion-seno-pdq| linfa|definition,audio|
|/types/breast/patient/breast-prevention-pdq| lung cancer|definition,pronunciation,audio,img[1]|
|/espanol/tipos/seno/paciente/prevencion-seno-pdq|heredados|definition,audio|
|/types/brain/patient/child-glioma-treatment-pdq| brain stem glioma|definition,pronunciation,audio,img[2]|
|/types/brain/hp/child-glioma-treatment-pdq|3-dimensional conformal radiation therapy|definition, pronunciation,audio|
|espanol/tipos/cerebro/paciente/tratamiento-cerebro-infantil-pdq|médula espinal|definition,audio,img[2]|
|/about-cancer/treatment/cam/patient/vitamin-c-pdq|G6PD deficiency| definition,pronunciation,audio|
|/about-cancer/treatment/cam/hp/vitamin-c-pdq|neuroblastoma| definition,pronunciation,audio,img[1]|
|/espanol/cancer/tratamiento/mca/paciente/vitamina-c-pdq|sangre| definition,audio,img[1]|
|/espanol/cancer/tratamiento/mca/pro/vitamina-c-pdq|colon|definition,audio,img[1]|
|/about-cancer/treatment/side-effects/fatigue/fatigue-pdq|platelet| definition,pronunciation,audio,img[1]|
|/espanol/cancer/tratamiento/efectos-secundarios/fatiga/fatiga-pdq|transfusiones| definition,audio,img[1]|
|/about-cancer/treatment/drugs/bevacizumab|metastasized|definition,pronunciation,audio,img[1]|
|/about-cancer/treatment/drugs/bep|malignant|definition,pronunciation,audio|

**Comment by kate-mashkina** [comment]
PR is merged
