### ISSUE TITLE
Update borderless card tests so that it takes care of the extra space in the title

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform-acceptance-tests#79]
### Issue description

Update borderless card tests so that it takes care of the extra space in the title. Currently the test for the title is failing because of the extra space in the title. Was noticed on ODE and dev-ac.

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/121535154-e443e480-c9cf-11eb-9cbe-abb2a214e4cb.png)
![image](https://user-images.githubusercontent.com/28455973/121535334-10f7fc00-c9d0-11eb-9fd0-329ceee7cf48.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by kate-mashkina** [comment]
@alinai can you verify if this is still an issue?

**Comment by alinai** [comment]
@KateMashkinaNIH , All AP tests are passing. So closing this one.
![image](https://user-images.githubusercontent.com/28455973/155370009-48f196e9-4ae9-4503-a328-7ed507b13162.png)
